/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafics;

import Abstract.Vehicule;
import Entities.BillBuyer;
import Entities.BranchOffice;
import Entities.Buyer;
import Entities.Purchases;
import Entities.Seler;
import static Grafics.Login.userMet;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Buy_with_Cash_Used extends javax.swing.JFrame {

    public  Buyer  persona;
    public  BranchOffice   sucursal;
    /**
     * Creates new form Buy_with_Cash_Used
     */
    public Buy_with_Cash_Used() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Ingresar Tarjeta");

        jLabel6.setText("Numero");

        jLabel7.setText("Codigo ");

        jLabel8.setText("Fecha de Vencimiento");

        jLabel3.setText("Placa del Vehiculo");

        jLabel33.setForeground(new java.awt.Color(0, 153, 153));
        jLabel33.setText("Dia");

        jLabel34.setForeground(new java.awt.Color(0, 153, 153));
        jLabel34.setText("Mes");

        jLabel35.setForeground(new java.awt.Color(0, 153, 153));
        jLabel35.setText("Año");

        jButton3.setText("Comprar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setText("Comprar Por Efectivo");

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafics/Imagenes/compra.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel33))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel34))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel35)
                                                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 90, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6)
                        .addGap(1, 1, 1))
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7))
                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try
        {
            int    placa=Integer.parseInt(jTextField2.getText());

            int number=Integer.parseInt(jTextField3.getText());
            int ping=Integer.parseInt(jTextField4.getText());
            String dia=(String) jComboBox4.getSelectedItem();
            String mes=(String) jComboBox5.getSelectedItem();
            String año=(String) jComboBox6.getSelectedItem();
            String fecha=dia+"/"+mes+"/"+año;

            if(persona != null)
            {
                boolean verifyCard=veriCardPersona(number,ping,fecha);
                if(verifyCard == true)
                {
                    buyPerson(placa);
                }
            }
            else
            {
                boolean verifyCard=veriCardSucursal(number,ping,fecha);
                if(verifyCard == true)
                {
                    buySucursal( placa);
                }
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Erro de datos");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login.BU.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

        public void buySucursal(int placa) // Comprar autos usados ,el comprador es tipo persona
    {
            Vehicule autoTObuy=verifyCar(placa); 
            
            if(autoTObuy != null) // Step 1
            {
                if(sucursal.myCard.get(0).getMoney() > autoTObuy.getPrice() )// Step 2
                {                    
                    // aqui agrego el auto a mi list
                    Seler seler=userMet.ReturnObjetSeler(autoTObuy.getIncharge()); // this met return the user with only the name
                    autoTObuy.setIncharge(sucursal.getName());// change the name of incharge
                    //
                    sucursal.boughtCars.add(autoTObuy);// add the vehicle in my list to buy
                    //
                    Login.selerMet.selerVehiculesList.remove(autoTObuy);
                    //
                    Login.vehiculesMet.vehiculesList.remove(autoTObuy); //delate of all sistem 
                    seler.deleteCar(autoTObuy.getLicensePlate());//delate of list of seler
                    
                    sucursal.myCard.get(0).setMoney(sucursal.myCard.get(0).getMoney()-autoTObuy.getPrice() );//aqui resto el monto del comprador
                    
                    BillBuyer  nuevo=new BillBuyer(sucursal.getName(),seler.getName(),autoTObuy.getNewOrused(),autoTObuy.getPrice(),autoTObuy.getLicensePlate(),autoTObuy.getBrand());
                    sucursal.record.add(nuevo);// agrego a mi historial de compras 
                    
                    // agrego a todas las compras
                    Purchases nuevoPurhase = new Purchases(autoTObuy.getType(),autoTObuy.getBrand(),autoTObuy.getLicensePlate(),autoTObuy.getPrice());
                    sucursal.purchases.add(nuevoPurhase);
                    
                    
                    
                    JOptionPane.showMessageDialog(null, "Factura: "+"\n"+"# Placa: "+autoTObuy.getLicensePlate()+"\n"+"Antiguo encargado: "+seler.getName()+"\n"+"Precio: "+autoTObuy.getPrice());
        
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"No tiene el dinero suficiente");
                }
            }
    }
    
   public Vehicule verifyCar(int placa)
   {
       for(Vehicule i: Login.vehiculesMet.vehiculesList)
       {
           if( i.getLicensePlate()== placa)
           {
               return i;
           }
       }
       return null;
   }
    public void buyPerson(int placa) // Comprar autos usados ,el comprador es tipo persona
    {
            Vehicule autoTObuy=verifyCar(placa); 
            
            if(autoTObuy != null) // Step 1
            {
                if(persona.myCard.get(0).getMoney() > autoTObuy.getPrice() )// Step 2
                {                    
                    // aqui agrego el auto a mi list
                    Seler seler=userMet.ReturnObjetSeler(autoTObuy.getIncharge()); // this met return the user with only the name
                    autoTObuy.setIncharge(persona.getName());// change the name of incharge
                    //
                    persona.boughtCars.add(autoTObuy);// add the vehicle in my list to buy
                    //
                    //
                    Login.selerMet.selerVehiculesList.remove(autoTObuy);
                    //
                    Login.vehiculesMet.vehiculesList.remove(autoTObuy); //delate of all sistem 
                    seler.deleteCar(autoTObuy.getLicensePlate());//delate of list of seler
                    
                    persona.myCard.get(0).setMoney(persona.myCard.get(0).getMoney()-autoTObuy.getPrice() );//aqui resto el monto del comprador
                    
                    BillBuyer  nuevo=new BillBuyer(persona.getName(),seler.getName(),autoTObuy.getNewOrused(),autoTObuy.getPrice(),autoTObuy.getLicensePlate(),autoTObuy.getBrand());
                    persona.record.add(nuevo);// agrego a mi historial de compras 
                    
                    // agrego a todas las compras
                    Purchases nuevoPurhase = new Purchases(autoTObuy.getType(),autoTObuy.getBrand(),autoTObuy.getLicensePlate(),autoTObuy.getPrice());
                    persona.purchases.add(nuevoPurhase);
                    
                    String Factura="Factura: "+"   "+"# Placa: "+autoTObuy.getLicensePlate()+"   Antiguo encargado: "+seler.getName()+" Precio: "+autoTObuy.getPrice();
                    
                    JOptionPane.showMessageDialog(null, Factura);
        
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"No tiene el dinero suficiente");
                }
            }
    }
    
    public boolean veriCardSucursal(int number,int ping,String fecha)
    {
        int cardNumber=sucursal.getCard().getNumber();
        int cardPing=sucursal.getCard().getPing();
        String cardFecha=sucursal.getCard().getDueDate();
        if(cardNumber == number)
        {
            if(cardPing==ping  )
            {
                
                if( cardFecha.equals(fecha) )
                {
                    return true;
                }
            }
            
        }

        return false;
        
    }
    
    public boolean veriCardPersona(int number,int ping,String fecha)
    {
        int cardNumber=persona.myCard.get(0).getNumber();
        int cardPing=persona.myCard.get(0).getPing();
        String cardFecha=persona.myCard.get(0).getDueDate();
        if(cardNumber == number)
        {
            if(cardPing==ping  )
            {
                
                if( cardFecha.equals(fecha) )
                {
                    return true;
                }
            }
            
        }

        return false;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buy_with_Cash_Used.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buy_with_Cash_Used.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buy_with_Cash_Used.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buy_with_Cash_Used.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buy_with_Cash_Used().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
